apiVersion: apps/v1 
kind: Deployment 
metadata: 
creationTimestamp: null 
labels: 
app: test 
name: test 
spec: 
replicas: 1 
selector: 
matchLabels: 
app: test 
strategy: () 
template: 
metadata: 
creationTimestamp: null 
labels: 
app: test 
spec: 
containers: 
image: nginx 
name: nginx 
volumeMounts: 
name: myfirst-vol 
mountPath: /usr/share/nginx/html 
volumes: 
name: myfirst-vol 
persistent VolumeClaim: 
claimName: myclaim